#!/usr/bin/env bash

chmod 700 ${HOME}/.config

# sparse checkout
rm -rf ${HOME}/README.md ${HOME}/UNLICENSE
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!UNLICENSE' '!Vagrantfile'

# create shell logging directory
mkdir -p ${HOME}/.logs

sh -c "$(wget https://starship.rs/install.sh -O -)" install -y --bin-dir ${HOME}/.local/bin/

wget git.io/antigen -O ${HOME}/.local/share/antigen.zsh
