#!/usr/bin/env bash

chmod 700 ${HOME}/.config

# sparse checkout
rm -rf ${HOME}/README.md ${HOME}/UNLICENSE
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!UNLICENSE' '!Vagrantfile'

# create shell logging directory
mkdir -p ${HOME}/.logs

sh -c "$(wget https://starship.rs/install.sh -O -)" install -y --bin-dir ${HOME}/.local/bin/

wget git.io/antigen -O ${HOME}/.local/share/antigen.zsh

TPM=${HOME}/.tmux/plugins/tpm
if [ -d $TPM/.git ]; then
    (
        cd ${TPM}

        git fetch origin

        # Make sure current branch is clean
        git clean -fd
        git reset --hard HEAD

        # Get on the desired branch
        git checkout master
        git reset --hard origin/master
    )
else
    rm -rf ${TPM}
    git clone https://github.com/tmux-plugins/tpm ${TPM}
fi

