#!/usr/bin/env sh

chmod 700 "${HOME}/.config"

# configure sparse checkout for yadm
rm -rf "${HOME}/README.md" "${HOME}/UNLICENSE"
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!UNLICENSE' '!Vagrantfile'

# create shell logging directory
mkdir -p "${HOME}/.logs"

# install starship
# sh -c "$(wget https://starship.rs/install.sh -O -)" install -y --bin-dir "${HOME}/.local/bin/"
curl -sSfL https://starship.rs/install.sh | sh -s -- -y --bin-dir "${HOME}/.local/bin/"

# install antigen
# wget git.io/antigen -O "${HOME}/.local/share/antigen.zsh"
curl -sSfLo "${HOME}/.local/share/antigen.zsh" git.io/antigen

# install tpm
TPM=${HOME}/.tmux/plugins/tpm
if [ -d "$TPM/.git" ]; then
    (
        cd "${TPM}" || exit

        git fetch origin

        # Make sure current branch is clean
        git clean -fd
        git reset --hard HEAD

        # Get on the desired branch
        git checkout master
        git reset --hard origin/master
    )
else
    rm -rf "${TPM}"
    git clone https://github.com/tmux-plugins/tpm "${TPM}"
fi

# install distillery
# bash -c "$(wget https://github.com/ekristen/distillery/releases/latest/download/installer.sh -O -)"
curl -sSfL "https://github.com/ekristen/distillery/releases/latest/download/installer.sh" | sh

